### ISSUE TITLE
Missing Header for the web page, update title and favicon

### ISSUE THREAD

**Issue by heraldjose10** [vaibhav-1508/expense-tracker#11]
Create a heading that says 'Expense Tracker'

**Comment by heraldjose10** [comment]
I would like to fix this if you can assign this to me

**Comment by vaibhav-1508** [comment]
Add the following to your issue heading and I'll assign it to you: https://github.com/vaibhav-1508/expense-tracker/issues/13 & https://github.com/vaibhav-1508/expense-tracker/issues/12

**Comment by heraldjose10** [comment]
I will complete the below things:

- [x] update favicon
- [x] change title
- [x] add a header

@vaibhav-1508 Sorry for creating separate issues earlier

**Comment by vaibhav-1508** [comment]
Cool, go ahead!

**Comment by heraldjose10** [comment]
Opened a PR #14 with the mentioned changes. Let me know if anything needs to be changed. Thanks
